### ISSUE TITLE
Erweiterter Image Editor

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/cropper#11]
Wirklich ein Nice To Have, aber manchmal sind hochgeladene Bilder noch zu dunkel etc. Vielleicht gibt es ja eine Library, die das einfach ermöglicht?

http://camanjs.com/ 
Ist ein Beispiel, das ich gefunden habe, das in die Richtung geht.

Oder http://fabricjs.com/image-filters

**Comment by joachimdoerr** [comment]
Naja eine JS lib bringt uns da wenig. Die Bilder werden serverseitig manipuliert, der "Editor" liefert nur die Informationen an php welches im Hintergrund schneidet und tut was es zu tun hat.

**Comment by skerbis** [comment]
Da fällt mir nur diese Lösung ein: https://ui.toast.com/tui-image-editor/

**Comment by cukabeka** [comment]
Oha, wow, das Toast Image Teil sieht sehr beeindruckend aus. Ist das denn für den Cropper nutzbar, also lässt sich das mit PHP verknüpfen?

**Comment by skerbis** [comment]
@cukabeka das wäre ein neues AddOn ... aber eben das was du suchst. Ich schließe das hier jetzt erstmal an dieser Stelle.
