### ISSUE TITLE
Frage: Hintergrundfarbe

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/cropper#12]
Wenn man ein Bild mit dem Cropper erweitert, wird der transparente Bereich schwarz gefärbt. Kann man irgendwo einstellen, welche Farbe für den Hintergrund verwendet wird? 

Schön wäre natürlich, wenn man das pro Bild einstellen könnte. Vorerst würde es mir aber  reichen, wenn ich das direkt im Code ändern könnte.

Vielen Dank, super Ding!

**Comment by skerbis** [comment]
Das müsste beim Vendor von Zebra_image gelöst werden, denke ich. 
https://github.com/stefangabos/Zebra_Image/issues/18

**Comment by skerbis** [comment]
https://github.com/stefangabos/Zebra_Image/issues/18
Kommt im nächsten Release

**Comment by skerbis** [comment]
längst erledigt
