### ISSUE TITLE
Größenänderung hinzufügen

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/cropper#15]
Es wäre schön, wenn zum Zuschnitt auch noch eine reine Funktion zur Größenänderung hinzukommen könnte.
Man hat ab und an immer mal den Fall, dass man ein Bild einfach nur kleiner rechnen möchten.

**Comment by skerbis** [comment]
Ich sehe hier keine solche Lösung beim Vendor: https://fengyuanchen.github.io/cropperjs/
