### ISSUE TITLE
Wunsch/Anregung: Editierbare "Aspect Ratios"

### ISSUE THREAD

**Issue by alexwenz** [FriendsOfREDAXO/cropper#16]
Habe gerade ein Projekt, bei dem es schön wäre, wenn man die Liste verfügbaren Seitenverhältnis-Optionen auszudünnen und mit eigenen zu versehen..

Wäre sowas denkbar?

**Comment by ansichtsache** [comment]
würde auch gerne ein seitenverhältnis ändern 2zu3 in 3zu2 – wo finde ich die code-stelle?
