### ISSUE TITLE
Nach Bearbeitung den Button "Übernehmen" erhalten

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/cropper#17]
Wird ein Bild bearbeitet, lässt es sich im Anschluss nicht mehr übernehmen.

**Comment by eaCe** [comment]
@alxndr-w wenn du möchtest kannst du den PR gerne mal testen.

**Comment by alxndr-w** [comment]
Ich habe das Addon nicht mehr im Einsatz, an sich sonst gerne.

**Comment by eaCe** [comment]
Ich auch nicht :D
