### ISSUE TITLE
Anordnung / Reihenfolge Bearbeiten-Button und zusätzliche Meta-Info Felder

### ISSUE THREAD

**Issue by ischfr** [FriendsOfREDAXO/cropper#22]
Wenn man zusätzliche Meta Info-Felder für Medien definiert hat, dann erscheinen diese erst nach dem Cropper-Button. 

**Beispiel:**
Titel _<- Standardfeld_
Medienkategorie _<- Standardfeld_
Cropper
Titel en _<- zus. Meta-Info_ 
Copyright _<- zus. Meta-Info_ 
Breite / Höhe
Dateiname
... usw

Es wäre m.E. schöner, wenn der Button erst nach evtl. vorhandenen Meta-Info-Feldern platziert sein könnte. Oder wenn man mittels irgendeiner Konfig oder Property Einfluss auf die Platzierung nehmen könnte.

**Comment by alexwenz** [comment]
Sehe keine sinnvolle Unterbringungsoption bei den gegebenen Möglichkeiten im Medienpool. Zudem ist die Position erlernt.

Gerne wieder öffnen, falls für Option gefunden.
