### ISSUE TITLE
cropper 1.4.0 assets/css/cropper.css unvollständig 

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/cropper#26]
**Description / Beschreibung**
assets/css/cropper.css unvollständig, wird im Medienpool daher nicht richtig dargestellt
siehe letzte Änderung: https://github.com/FriendsOfREDAXO/cropper/commit/63a1ca2be9b0406e1b39c213d8f9889bbc2a0fc0#diff-91f4b339712291fd4daa8263dc33a65ff93d2a4fa89a942d99f99763fe050516

**Affected versions / Verwendete Versionen**
1.4.0

**Comment by alexwenz** [comment]
CSS ist wieder eingefügt. Schließe das Issue...
