### ISSUE TITLE
Individuelle Ratios definieren

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/cropper#3]

**Comment by seeyouonline** [comment]
Vielleicht wäre es auch möglich, die Länge und Breite des gewünschten Bildes per Inputfelder vorzugeben, statt einer Ratio? Die Benutzer wissen ja meist wie groß die Bilder an bestimmten Stellen sein müssen, aber die Ratio davon wissen sie meist nicht.

**Comment by skerbis** [comment]
Um die Größen kümmert sich der MediaManager. Es geht hier darum die Bilder im richtigen Seitenverhältnis zuzuschneiden. Welches Seitenverhältnis muss die gestaltende Agentur dem Redakteur ggf. mitteilen. Ich sehe das AddOn als Hilfsmittel zur Korrektur an. Vor allem wenn man man ein Bild drehen muss oder wenn der Ausschnitt nicht perfekt gewählt ist.
