### ISSUE TITLE
Übernehmen Button wird in der Medienliste je Medium nicht mehr angezeigt

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/cropper#46]
Wenn die Rolle nicht das Recht CROPPER[] hat.

**Comment by alexwenz** [comment]
@eaCe ich glaube, das hat mit Deinem PR (https://github.com/FriendsOfREDAXO/cropper/pull/40) zu tun. Haste ne Idee, wie wir das wieder hinbekommen?

Also ein normaler Redakteur ohne Cropper-Rechte sieht nirgends mehr einen Übernehmen-Button, sobald 

`if (!rex::getUser()->hasPerm('cropper[]')) return false; // don't show the button`

im EP aufgerufen wird...

**Comment by eaCe** [comment]
@skerbis @alexwenz ich dachte das war so gewünscht: https://github.com/FriendsOfREDAXO/cropper/issues/39 
In den Einstellungen kann dieser eingeblendet werden

**Comment by alexwenz** [comment]
@eaCe aktuell sieht ein Nutzer, der keinen zugriff auf cropper hat (also auch nicht auf die Einstellungsseite) überhaupt keinen Übernehmen-Button mehr, wenn er lediglich ein Bild aus dem Medienpool auswählen möchte.

Ich glaube wenn ich anstatt "return false" "return $ep->subject" mache, gehts:

`if (!rex::getUser()->hasPerm('cropper[]')) return $ep->getSubject(); // don't show the button`

**Comment by eaCe** [comment]
Achso, das habe ich falsch verstanden. Ich schaue nach

**Comment by skerbis** [comment]
@eaCe @alexwenz aus versehen gemerged. 
Bitte mal die aktuelle boot.php checken.

**Comment by eaCe** [comment]
Die genannte Zeile kam nicht von mir
https://github.com/FriendsOfREDAXO/cropper/commit/691f1ac357aabce22e1e72bead0827fbcf45c1eb

**Comment by alexwenz** [comment]
@skerbis passt für mich.

@skerbis @eaCe ich hab noch ein wenig an der Ausgabe gebastelt und würde gerne den cropper-button und den übernehmen in einer Zeile einbauen:

![image](https://user-images.githubusercontent.com/5278794/236435842-0b11405e-d242-44df-bcf2-df645a5d67e3.png)

**Comment by eaCe** [comment]
Für mich passt das
