### ISSUE TITLE
Anregung: Backup der Originaldatei / "Zurück zum Original"

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/cropper#5]
Man könnte vielleicht auch überlegen, dass (optional) ein Backup der Originaldatei irgendwo anders abgelegt wird. 
Man würde also schon die eine gerade geöffnete Datei direkt bearbeiten. Aus Außensicht gibt es danach also nur die geänderte Datei. 
Aber man könnte dann trotzdem einen Button “Zurück zum Original” anbieten.

**Comment by joachimdoerr** [comment]
Eine gute Idee, man könnte temporär die letzten x Dateien im addon data folder halten. und bei Aufruf des Medienpools einfach alle die über den count vorhanden sort by creation date weglöschen, die Verfügbarkeit des buttons könnte man an die vorhandenheit der temp-datei knüpfen.

**Comment by alexwenz** [comment]
Durch die Option "als neue Datei speichern" abgedeckt. Deshalb schließe ich Mal nach 4 Jahren :-)
