### ISSUE TITLE
`test` notice – braucht man das oder kann das weg?

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/cropper#50]
https://github.com/FriendsOfREDAXO/cropper/blob/a29364ca60b2f891f8d92b380c12f4ae0215ffab/install.php#L5

irgendwie unschön ;)

**Comment by alxndr-w** [comment]
Kann bestimmt weg, wenn's keine Antwort gab. Du machst den PR?

**Comment by skerbis** [comment]
erledigt
