### ISSUE TITLE
Wunsch: optional: Zoom per Mausrad ausschalten

### ISSUE THREAD

**Issue by danspringer** [FriendsOfREDAXO/cropper#6]
Da der Medienpool in einem recht kleinen Pop-Up geöffnet wird, scrollt man gerne mal das Fenster runter, um dann die Einstellungen z.B. für den neuen Cropper-Dateinamen einzugeben. Wenn man dann mit der Maus über dem Arbeitsbereich steht, zoomt man sich seinen Ausschnitt weg.

Ich finde der Zoom über die Buttons ist ausreichend und auch genauer zu benutzen als mit dem Mausrad.

**Comment by joachimdoerr** [comment]
sehe das genauso. gibt es hier Einwände sonst würde ich das für den nächsten release vorsehen.

**Comment by skerbis** [comment]
auf dem Trackpad ist es super wie es ist. … ggf. optional

**Comment by joachimdoerr** [comment]
ich hab da aber auch mit dem trackpad probleme

**Comment by skerbis** [comment]
Ich mag die Funktion eigentlich. Da sie präziser als die Plus und Minus-Buttons sind. 
Ich denke wir sollten es als Option anbieten.

**Comment by alexwenz** [comment]
Ist initial ausgeschaltet und kann über einen Settings-Button oben rechts auf Wunsch wieder eingeschaltet werden. Bitte mal testen, ob für Euch OK.
