### ISSUE TITLE
Rotate-Left and Rotate-Right Änderungen werden nicht übernommen

### ISSUE THREAD

**Issue by danspringer** [FriendsOfREDAXO/cropper#7]
Änderungen, die mit Rotate-Left oder right gemacht werden, werden nicht übernommen. Es wird zwar gecroppt, aber nicht gedreht.

Rex: 5.7.0-beta2
PHP 7.1.26

Cache gelöscht

**Comment by joachimdoerr** [comment]
kann das sonst noch jemand verifizieren, bei meinen letzten test versuchen ging es

**Comment by danspringer** [comment]
Habe dieses Verhalten in drei Unterschiedlichen Installationen reproduzieren können.

**Comment by joachimdoerr** [comment]
eventuell kommt das nur bei negativen rotations werten vor?

**Comment by joachimdoerr** [comment]
das müsste != sein.
https://github.com/FriendsOfREDAXO/cropper/blob/master/lib/Cropper/CropperExecutor.php#L176

**Comment by danspringer** [comment]
Ja, tatsächlich geht nur Rotate left nicht. Right funktioniert.

**Comment by joachimdoerr** [comment]
bitte nochmal testen mit : https://github.com/FriendsOfREDAXO/cropper/commit/877e7b8b5811f165eacf13e366db6a7799b2e04e

**Comment by danspringer** [comment]
> bitte nochmal testen mit : [877e7b8](https://github.com/FriendsOfREDAXO/cropper/commit/877e7b8b5811f165eacf13e366db6a7799b2e04e)

Funktioniert so.

**Comment by joachimdoerr** [comment]
dann close.
